[jwt]
default = false

[http]
port = 6000 

[pg]
host = "desarrollo.horus.es"
user = "pablo.leon"
pass = "emerson.67"
port = 5432
database = "milenio-suscriptor-2-26-es"

[queries]
location = "/Users/pablo/nt/prest/ejemplo/queries"
